import AppKit
import CryptoKit
import Foundation
import ImageIO
import NotchiumCore
import UniformTypeIdentifiers

public enum ClipboardItemKind: String, Codable, Sendable {
    case text, url, image, file
}

/// One supported clipboard value. Images are already downsampled: a bounded PNG to copy back
/// and a tiny thumbnail for the list.
public enum ClipboardContent: Equatable, Sendable {
    case text(String)
    case url(URL)
    case image(png: Data, thumbnail: Data, pixelSize: CGSize)
    case files([URL])

    public var kind: ClipboardItemKind {
        switch self {
        case .text: .text
        case .url: .url
        case .image: .image
        case .files: .file
        }
    }

    /// Identity for "copied again → move to front". Images compare by their stored bytes.
    public var fingerprint: String {
        let bytes: Data = switch self {
        case let .text(text): Data(("t:" + text).utf8)
        case let .url(url): Data(("u:" + url.absoluteString).utf8)
        case let .image(png, _, _): png
        case let .files(urls): Data(("f:" + urls.map(\.path).joined(separator: "\n")).utf8)
        }
        return SHA256.hash(data: bytes).map { String(format: "%02x", $0) }.joined()
    }
}

public struct ClipboardCapture: Equatable, Sendable {
    public let content: ClipboardContent
    public let capturedAt: Date
    public init(content: ClipboardContent, capturedAt: Date) {
        self.content = content
        self.capturedAt = capturedAt
    }
}

public protocol ClipboardService: Sendable {
    func availability() async -> FeatureAvailability
    /// New clipboard values copied by other apps. Notchium's own writes are not reported.
    func captures() async -> AsyncStream<ClipboardCapture>
    func write(_ content: ClipboardContent) async
}

/// Which pasteboard contents are never recorded. Password managers mark secrets with the
/// community `org.nspasteboard` types; a few known managers are also excluded by source app.
/// This is best effort: macOS does not tell a clipboard observer whether data is sensitive.
public enum ClipboardPrivacyPolicy {
    public static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "com.typeit4me.clipping", "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type", "net.antelle.keeweb",
    ]
    public static let excludedApplications: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.agilebits.onepassword-osx",
        "com.bitwarden.desktop", "com.apple.keychainaccess", "com.apple.Passwords",
        "org.keepassxc.keepassxc", "com.lastpass.LastPass", "com.dashlane.dashlanephonefinal",
        "in.sinew.Enpass-Desktop", "com.nordpass.macos.NordPass",
    ]
    /// Larger values are not kept (pasted logs, data dumps).
    public static let maximumTextLength = 100_000

    public static func isExcluded(types: [String], sourceBundleID: String?) -> Bool {
        if let sourceBundleID, excludedApplications.contains(sourceBundleID) { return true }
        return types.contains { excludedTypes.contains($0) }
    }
}

/// `NSPasteboard` has no change notification; its integer change count is read twice a second
/// on the main thread, and contents are read only when that count moves.
@MainActor
public final class RealClipboardService: ClipboardService {
    private let pasteboard: NSPasteboard
    private var ownChangeCount: Int?
    private var continuations: [UUID: AsyncStream<ClipboardCapture>.Continuation] = [:]
    private var timer: Timer?
    private var lastChangeCount: Int
    private var imageTask: Task<Void, Never>?
    private var generation = 0
    private let processImage: @Sendable (Data) async -> ClipboardContent?

    public convenience init(pasteboard: NSPasteboard = .general) {
        self.init(pasteboard: pasteboard, processImage: ClipboardImageProcessing.process)
    }

    init(pasteboard: NSPasteboard, processImage: @escaping @Sendable (Data) async -> ClipboardContent?) {
        self.pasteboard = pasteboard
        self.processImage = processImage
        lastChangeCount = pasteboard.changeCount
    }

    isolated deinit {
        timer?.invalidate()
        imageTask?.cancel()
    }

    public func availability() async -> FeatureAvailability { .available }

    public func captures() async -> AsyncStream<ClipboardCapture> {
        let (stream, continuation) = AsyncStream<ClipboardCapture>.makeStream(bufferingPolicy: .bufferingNewest(8))
        let id = UUID()
        continuations[id] = continuation
        continuation.onTermination = { [weak self] _ in
            Task { @MainActor in self?.remove(id) }
        }
        startPolling()
        return stream
    }

    public func write(_ content: ClipboardContent) async {
        invalidateImage()
        pasteboard.clearContents()
        switch content {
        case let .text(text): pasteboard.setString(text, forType: .string)
        case let .url(url):
            pasteboard.writeObjects([url as NSURL])
            pasteboard.setString(url.absoluteString, forType: .string)
        case let .image(png, _, _): pasteboard.setData(png, forType: .png)
        case let .files(urls): pasteboard.writeObjects(urls.map { $0 as NSURL })
        }
        ownChangeCount = pasteboard.changeCount
        lastChangeCount = pasteboard.changeCount
    }

    private func remove(_ id: UUID) {
        continuations[id] = nil
        guard continuations.isEmpty else { return }
        invalidateImage()
        timer?.invalidate()
        timer = nil
    }

    private func startPolling() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        invalidateImage()
        lastChangeCount = count
        guard count != ownChangeCount else { return }
        let types = pasteboard.types?.map(\.rawValue) ?? []
        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        guard !ClipboardPrivacyPolicy.isExcluded(types: types, sourceBundleID: source) else { return }
        let now = Date()
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            emit(.init(content: .files(urls), capturedAt: now))
        } else if let raw = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
            // Decoding and downsampling happen off the main thread.
            let generation = generation
            imageTask = Task(priority: .utility) { [weak self, processImage] in
                let content = await processImage(raw)
                guard let self, !Task.isCancelled, self.generation == generation,
                      self.lastChangeCount == count, self.pasteboard.changeCount == count else { return }
                self.imageTask = nil
                if let content { self.emit(.init(content: content, capturedAt: now)) }
            }
        } else if let url = Self.webURL(from: pasteboard) {
            emit(.init(content: .url(url), capturedAt: now))
        } else if let text = pasteboard.string(forType: .string),
                  !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                  text.count <= ClipboardPrivacyPolicy.maximumTextLength {
            emit(.init(content: .text(text), capturedAt: now))
        }
    }

    private func invalidateImage() {
        generation &+= 1
        imageTask?.cancel()
        imageTask = nil
    }

    private func emit(_ capture: ClipboardCapture) {
        continuations.values.forEach { $0.yield(capture) }
    }

    /// A copied link: an explicit URL type, or a single line of text that is an http(s) URL.
    static func webURL(from pasteboard: NSPasteboard) -> URL? {
        if let url = (pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL])?.first,
           ["http", "https"].contains(url.scheme?.lowercased() ?? "") { return url }
        guard let text = pasteboard.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
              !text.contains(where: \.isWhitespace), let url = URL(string: text),
              ["http", "https"].contains(url.scheme?.lowercased() ?? ""), url.host != nil else { return nil }
        return url
    }
}

public enum ClipboardImageProcessing {
    /// Long edge of the stored image that is copied back.
    public static let maximumPixelSize = 2048
    public static let thumbnailPixelSize = 96

    @concurrent static func process(_ data: Data) async -> ClipboardContent? {
        guard !Task.isCancelled else { return nil }
        return content(from: data)
    }

    public static func content(from data: Data) -> ClipboardContent? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let full = downsample(source, to: maximumPixelSize),
              let thumbnail = downsample(source, to: thumbnailPixelSize),
              let png = pngData(full), let thumbnailData = pngData(thumbnail) else { return nil }
        return .image(png: png, thumbnail: thumbnailData, pixelSize: CGSize(width: full.width, height: full.height))
    }

    private static func downsample(_ source: CGImageSource, to size: Int) -> CGImage? {
        CGImageSourceCreateThumbnailAtIndex(source, 0, [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: size,
        ] as CFDictionary)
    }

    private static func pngData(_ image: CGImage) -> Data? {
        let data = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(data, UTType.png.identifier as CFString, 1, nil)
        else { return nil }
        CGImageDestinationAddImage(destination, image, nil)
        return CGImageDestinationFinalize(destination) ? data as Data : nil
    }
}

/// Test double: `send` delivers a capture; `written` records copy-backs.
public final class MockClipboardService: ClipboardService, @unchecked Sendable {
    private let lock = NSLock()
    private var continuations: [UUID: AsyncStream<ClipboardCapture>.Continuation] = [:]
    private var writes: [ClipboardContent] = []

    public init() {}

    public var written: [ClipboardContent] { lock.withLock { writes } }

    public func availability() async -> FeatureAvailability { .available }

    public func captures() async -> AsyncStream<ClipboardCapture> {
        let (stream, continuation) = AsyncStream<ClipboardCapture>.makeStream()
        let id = UUID()
        lock.withLock { continuations[id] = continuation }
        continuation.onTermination = { [weak self] _ in
            guard let self else { return }
            _ = self.lock.withLock { self.continuations.removeValue(forKey: id) }
        }
        return stream
    }

    public func write(_ content: ClipboardContent) async {
        lock.withLock { writes.append(content) }
    }

    public func send(_ capture: ClipboardCapture) {
        let targets = lock.withLock { Array(continuations.values) }
        targets.forEach { $0.yield(capture) }
    }
}
